/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthenticatedRouteImport } from './routes/_unauthenticated'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as UnauthenticatedRegisterRouteImport } from './routes/_unauthenticated/register'
import { Route as AuthenticatedBlockedRouteImport } from './routes/_authenticated/blocked'
import { Route as AuthenticatedLayoutRouteImport } from './routes/_authenticated/_layout'
import { Route as UnauthenticatedRecoveryRouteRouteImport } from './routes/_unauthenticated/recovery.route'
import { Route as UnauthenticatedLoginRouteRouteImport } from './routes/_unauthenticated/login.route'
import { Route as UnauthenticatedRecoveryIndexRouteImport } from './routes/_unauthenticated/recovery.index'
import { Route as UnauthenticatedLoginIndexRouteImport } from './routes/_unauthenticated/login.index'
import { Route as AuthenticatedLayoutIndexRouteImport } from './routes/_authenticated/_layout.index'
import { Route as UnauthenticatedRecoveryCodeRouteImport } from './routes/_unauthenticated/recovery.code'
import { Route as UnauthenticatedLoginEmailRouteImport } from './routes/_unauthenticated/login.email'
import { Route as AuthenticatedLayoutProfileRouteImport } from './routes/_authenticated/_layout.profile'
import { Route as AuthenticatedLayoutGroupsGroupIdRouteImport } from './routes/_authenticated/_layout.groups.$groupId'

const UnauthenticatedRoute = UnauthenticatedRouteImport.update({
  id: '/_unauthenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthenticatedRegisterRoute = UnauthenticatedRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => UnauthenticatedRoute,
} as any)
const AuthenticatedBlockedRoute = AuthenticatedBlockedRouteImport.update({
  id: '/blocked',
  path: '/blocked',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLayoutRoute = AuthenticatedLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const UnauthenticatedRecoveryRouteRoute =
  UnauthenticatedRecoveryRouteRouteImport.update({
    id: '/recovery',
    path: '/recovery',
    getParentRoute: () => UnauthenticatedRoute,
  } as any)
const UnauthenticatedLoginRouteRoute =
  UnauthenticatedLoginRouteRouteImport.update({
    id: '/login',
    path: '/login',
    getParentRoute: () => UnauthenticatedRoute,
  } as any)
const UnauthenticatedRecoveryIndexRoute =
  UnauthenticatedRecoveryIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => UnauthenticatedRecoveryRouteRoute,
  } as any)
const UnauthenticatedLoginIndexRoute =
  UnauthenticatedLoginIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => UnauthenticatedLoginRouteRoute,
  } as any)
const AuthenticatedLayoutIndexRoute =
  AuthenticatedLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const UnauthenticatedRecoveryCodeRoute =
  UnauthenticatedRecoveryCodeRouteImport.update({
    id: '/code',
    path: '/code',
    getParentRoute: () => UnauthenticatedRecoveryRouteRoute,
  } as any)
const UnauthenticatedLoginEmailRoute =
  UnauthenticatedLoginEmailRouteImport.update({
    id: '/email',
    path: '/email',
    getParentRoute: () => UnauthenticatedLoginRouteRoute,
  } as any)
const AuthenticatedLayoutProfileRoute =
  AuthenticatedLayoutProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedLayoutGroupsGroupIdRoute =
  AuthenticatedLayoutGroupsGroupIdRouteImport.update({
    id: '/groups/$groupId',
    path: '/groups/$groupId',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof UnauthenticatedLoginRouteRouteWithChildren
  '/recovery': typeof UnauthenticatedRecoveryRouteRouteWithChildren
  '/blocked': typeof AuthenticatedBlockedRoute
  '/register': typeof UnauthenticatedRegisterRoute
  '/profile': typeof AuthenticatedLayoutProfileRoute
  '/login/email': typeof UnauthenticatedLoginEmailRoute
  '/recovery/code': typeof UnauthenticatedRecoveryCodeRoute
  '/': typeof AuthenticatedLayoutIndexRoute
  '/login/': typeof UnauthenticatedLoginIndexRoute
  '/recovery/': typeof UnauthenticatedRecoveryIndexRoute
  '/groups/$groupId': typeof AuthenticatedLayoutGroupsGroupIdRoute
}
export interface FileRoutesByTo {
  '/blocked': typeof AuthenticatedBlockedRoute
  '/register': typeof UnauthenticatedRegisterRoute
  '/profile': typeof AuthenticatedLayoutProfileRoute
  '/login/email': typeof UnauthenticatedLoginEmailRoute
  '/recovery/code': typeof UnauthenticatedRecoveryCodeRoute
  '/': typeof AuthenticatedLayoutIndexRoute
  '/login': typeof UnauthenticatedLoginIndexRoute
  '/recovery': typeof UnauthenticatedRecoveryIndexRoute
  '/groups/$groupId': typeof AuthenticatedLayoutGroupsGroupIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_unauthenticated': typeof UnauthenticatedRouteWithChildren
  '/_unauthenticated/login': typeof UnauthenticatedLoginRouteRouteWithChildren
  '/_unauthenticated/recovery': typeof UnauthenticatedRecoveryRouteRouteWithChildren
  '/_authenticated/_layout': typeof AuthenticatedLayoutRouteWithChildren
  '/_authenticated/blocked': typeof AuthenticatedBlockedRoute
  '/_unauthenticated/register': typeof UnauthenticatedRegisterRoute
  '/_authenticated/_layout/profile': typeof AuthenticatedLayoutProfileRoute
  '/_unauthenticated/login/email': typeof UnauthenticatedLoginEmailRoute
  '/_unauthenticated/recovery/code': typeof UnauthenticatedRecoveryCodeRoute
  '/_authenticated/_layout/': typeof AuthenticatedLayoutIndexRoute
  '/_unauthenticated/login/': typeof UnauthenticatedLoginIndexRoute
  '/_unauthenticated/recovery/': typeof UnauthenticatedRecoveryIndexRoute
  '/_authenticated/_layout/groups/$groupId': typeof AuthenticatedLayoutGroupsGroupIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/recovery'
    | '/blocked'
    | '/register'
    | '/profile'
    | '/login/email'
    | '/recovery/code'
    | '/'
    | '/login/'
    | '/recovery/'
    | '/groups/$groupId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/blocked'
    | '/register'
    | '/profile'
    | '/login/email'
    | '/recovery/code'
    | '/'
    | '/login'
    | '/recovery'
    | '/groups/$groupId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_unauthenticated'
    | '/_unauthenticated/login'
    | '/_unauthenticated/recovery'
    | '/_authenticated/_layout'
    | '/_authenticated/blocked'
    | '/_unauthenticated/register'
    | '/_authenticated/_layout/profile'
    | '/_unauthenticated/login/email'
    | '/_unauthenticated/recovery/code'
    | '/_authenticated/_layout/'
    | '/_unauthenticated/login/'
    | '/_unauthenticated/recovery/'
    | '/_authenticated/_layout/groups/$groupId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  UnauthenticatedRoute: typeof UnauthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_unauthenticated': {
      id: '/_unauthenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof UnauthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_unauthenticated/register': {
      id: '/_unauthenticated/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof UnauthenticatedRegisterRouteImport
      parentRoute: typeof UnauthenticatedRoute
    }
    '/_authenticated/blocked': {
      id: '/_authenticated/blocked'
      path: '/blocked'
      fullPath: '/blocked'
      preLoaderRoute: typeof AuthenticatedBlockedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_layout': {
      id: '/_authenticated/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedLayoutRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_unauthenticated/recovery': {
      id: '/_unauthenticated/recovery'
      path: '/recovery'
      fullPath: '/recovery'
      preLoaderRoute: typeof UnauthenticatedRecoveryRouteRouteImport
      parentRoute: typeof UnauthenticatedRoute
    }
    '/_unauthenticated/login': {
      id: '/_unauthenticated/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof UnauthenticatedLoginRouteRouteImport
      parentRoute: typeof UnauthenticatedRoute
    }
    '/_unauthenticated/recovery/': {
      id: '/_unauthenticated/recovery/'
      path: '/'
      fullPath: '/recovery/'
      preLoaderRoute: typeof UnauthenticatedRecoveryIndexRouteImport
      parentRoute: typeof UnauthenticatedRecoveryRouteRoute
    }
    '/_unauthenticated/login/': {
      id: '/_unauthenticated/login/'
      path: '/'
      fullPath: '/login/'
      preLoaderRoute: typeof UnauthenticatedLoginIndexRouteImport
      parentRoute: typeof UnauthenticatedLoginRouteRoute
    }
    '/_authenticated/_layout/': {
      id: '/_authenticated/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedLayoutIndexRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_unauthenticated/recovery/code': {
      id: '/_unauthenticated/recovery/code'
      path: '/code'
      fullPath: '/recovery/code'
      preLoaderRoute: typeof UnauthenticatedRecoveryCodeRouteImport
      parentRoute: typeof UnauthenticatedRecoveryRouteRoute
    }
    '/_unauthenticated/login/email': {
      id: '/_unauthenticated/login/email'
      path: '/email'
      fullPath: '/login/email'
      preLoaderRoute: typeof UnauthenticatedLoginEmailRouteImport
      parentRoute: typeof UnauthenticatedLoginRouteRoute
    }
    '/_authenticated/_layout/profile': {
      id: '/_authenticated/_layout/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedLayoutProfileRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticated/_layout/groups/$groupId': {
      id: '/_authenticated/_layout/groups/$groupId'
      path: '/groups/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof AuthenticatedLayoutGroupsGroupIdRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
  }
}

interface AuthenticatedLayoutRouteChildren {
  AuthenticatedLayoutProfileRoute: typeof AuthenticatedLayoutProfileRoute
  AuthenticatedLayoutIndexRoute: typeof AuthenticatedLayoutIndexRoute
  AuthenticatedLayoutGroupsGroupIdRoute: typeof AuthenticatedLayoutGroupsGroupIdRoute
}

const AuthenticatedLayoutRouteChildren: AuthenticatedLayoutRouteChildren = {
  AuthenticatedLayoutProfileRoute: AuthenticatedLayoutProfileRoute,
  AuthenticatedLayoutIndexRoute: AuthenticatedLayoutIndexRoute,
  AuthenticatedLayoutGroupsGroupIdRoute: AuthenticatedLayoutGroupsGroupIdRoute,
}

const AuthenticatedLayoutRouteWithChildren =
  AuthenticatedLayoutRoute._addFileChildren(AuthenticatedLayoutRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedLayoutRoute: typeof AuthenticatedLayoutRouteWithChildren
  AuthenticatedBlockedRoute: typeof AuthenticatedBlockedRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedLayoutRoute: AuthenticatedLayoutRouteWithChildren,
  AuthenticatedBlockedRoute: AuthenticatedBlockedRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface UnauthenticatedLoginRouteRouteChildren {
  UnauthenticatedLoginEmailRoute: typeof UnauthenticatedLoginEmailRoute
  UnauthenticatedLoginIndexRoute: typeof UnauthenticatedLoginIndexRoute
}

const UnauthenticatedLoginRouteRouteChildren: UnauthenticatedLoginRouteRouteChildren =
  {
    UnauthenticatedLoginEmailRoute: UnauthenticatedLoginEmailRoute,
    UnauthenticatedLoginIndexRoute: UnauthenticatedLoginIndexRoute,
  }

const UnauthenticatedLoginRouteRouteWithChildren =
  UnauthenticatedLoginRouteRoute._addFileChildren(
    UnauthenticatedLoginRouteRouteChildren,
  )

interface UnauthenticatedRecoveryRouteRouteChildren {
  UnauthenticatedRecoveryCodeRoute: typeof UnauthenticatedRecoveryCodeRoute
  UnauthenticatedRecoveryIndexRoute: typeof UnauthenticatedRecoveryIndexRoute
}

const UnauthenticatedRecoveryRouteRouteChildren: UnauthenticatedRecoveryRouteRouteChildren =
  {
    UnauthenticatedRecoveryCodeRoute: UnauthenticatedRecoveryCodeRoute,
    UnauthenticatedRecoveryIndexRoute: UnauthenticatedRecoveryIndexRoute,
  }

const UnauthenticatedRecoveryRouteRouteWithChildren =
  UnauthenticatedRecoveryRouteRoute._addFileChildren(
    UnauthenticatedRecoveryRouteRouteChildren,
  )

interface UnauthenticatedRouteChildren {
  UnauthenticatedLoginRouteRoute: typeof UnauthenticatedLoginRouteRouteWithChildren
  UnauthenticatedRecoveryRouteRoute: typeof UnauthenticatedRecoveryRouteRouteWithChildren
  UnauthenticatedRegisterRoute: typeof UnauthenticatedRegisterRoute
}

const UnauthenticatedRouteChildren: UnauthenticatedRouteChildren = {
  UnauthenticatedLoginRouteRoute: UnauthenticatedLoginRouteRouteWithChildren,
  UnauthenticatedRecoveryRouteRoute:
    UnauthenticatedRecoveryRouteRouteWithChildren,
  UnauthenticatedRegisterRoute: UnauthenticatedRegisterRoute,
}

const UnauthenticatedRouteWithChildren = UnauthenticatedRoute._addFileChildren(
  UnauthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  UnauthenticatedRoute: UnauthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
